[2025-01-05T16:58:36.164+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-05T16:58:36.180+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing2_vsc.is_api_available scheduled__2025-01-05T16:58:00+00:00 [queued]>
[2025-01-05T16:58:36.186+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing2_vsc.is_api_available scheduled__2025-01-05T16:58:00+00:00 [queued]>
[2025-01-05T16:58:36.187+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-05T16:58:36.198+0000] {taskinstance.py:2889} INFO - Executing <Task(HttpSensor): is_api_available> on 2025-01-05 16:58:00+00:00
[2025-01-05T16:58:36.206+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3827) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-05T16:58:36.207+0000] {standard_task_runner.py:72} INFO - Started process 3829 to run task
[2025-01-05T16:58:36.208+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_processing2_vsc', 'is_api_available', 'scheduled__2025-01-05T16:58:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/user_dag.py', '--cfg-path', '/tmp/tmpnvzh94m8']
[2025-01-05T16:58:36.208+0000] {standard_task_runner.py:105} INFO - Job 89: Subtask is_api_available
[2025-01-05T16:58:36.245+0000] {task_command.py:467} INFO - Running <TaskInstance: user_processing2_vsc.is_api_available scheduled__2025-01-05T16:58:00+00:00 [running]> on host cab0b5f06594
[2025-01-05T16:58:36.318+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing2_vsc' AIRFLOW_CTX_TASK_ID='is_api_available' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T16:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-05T16:58:00+00:00'
[2025-01-05T16:58:36.320+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-05T16:58:36.320+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-05T16:58:36.320+0000] {logging_mixin.py:190} INFO - Current task name:is_api_available state:running start_date:2025-01-05 16:58:36.180858+00:00
[2025-01-05T16:58:36.320+0000] {logging_mixin.py:190} INFO - Dag name:user_processing2_vsc and current dag run status:running
[2025-01-05T16:58:36.320+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-05T16:58:36.321+0000] {baseoperator.py:421} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2025-01-05T16:58:36.321+0000] {http.py:139} INFO - Poking: api/
[2025-01-05T16:58:36.328+0000] {base.py:84} INFO - Retrieving connection 'user_api'
[2025-01-05T16:58:36.456+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2025-01-05T16:58:36.481+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-05T16:58:36.483+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=user_processing2_vsc, task_id=is_api_available, run_id=scheduled__2025-01-05T16:58:00+00:00, execution_date=20250105T165800, start_date=20250105T165836, end_date=20250105T165836
[2025-01-05T16:58:36.504+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-05T16:58:36.504+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-05T16:58:36.504+0000] {logging_mixin.py:190} INFO - Dag name:user_processing2_vsc queued_at:2025-01-05 16:59:21.447695+00:00
[2025-01-05T16:58:36.505+0000] {logging_mixin.py:190} INFO - Task hostname:cab0b5f06594 operator:HttpSensor
[2025-01-05T16:58:36.527+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-05T16:58:36.584+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-05T16:58:36.588+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
