[2025-01-05T21:08:39.107+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-05T21:08:39.120+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing2_vsc.is_api_available scheduled__2025-01-05T21:07:00+00:00 [queued]>
[2025-01-05T21:08:39.126+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing2_vsc.is_api_available scheduled__2025-01-05T21:07:00+00:00 [queued]>
[2025-01-05T21:08:39.127+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-05T21:08:39.138+0000] {taskinstance.py:2889} INFO - Executing <Task(HttpSensor): is_api_available> on 2025-01-05 21:07:00+00:00
[2025-01-05T21:08:39.144+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5822) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-05T21:08:39.146+0000] {standard_task_runner.py:72} INFO - Started process 5824 to run task
[2025-01-05T21:08:39.147+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_processing2_vsc', 'is_api_available', 'scheduled__2025-01-05T21:07:00+00:00', '--job-id', '260', '--raw', '--subdir', 'DAGS_FOLDER/user_dag.py', '--cfg-path', '/tmp/tmpzpya6itk']
[2025-01-05T21:08:39.147+0000] {standard_task_runner.py:105} INFO - Job 260: Subtask is_api_available
[2025-01-05T21:08:39.185+0000] {task_command.py:467} INFO - Running <TaskInstance: user_processing2_vsc.is_api_available scheduled__2025-01-05T21:07:00+00:00 [running]> on host cab0b5f06594
[2025-01-05T21:08:39.422+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing2_vsc' AIRFLOW_CTX_TASK_ID='is_api_available' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T21:07:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-05T21:07:00+00:00'
[2025-01-05T21:08:39.422+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-05T21:08:39.422+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-05T21:08:39.423+0000] {logging_mixin.py:190} INFO - Current task name:is_api_available state:running start_date:2025-01-05 21:08:39.120583+00:00
[2025-01-05T21:08:39.423+0000] {logging_mixin.py:190} INFO - Dag name:user_processing2_vsc and current dag run status:running
[2025-01-05T21:08:39.423+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-05T21:08:39.423+0000] {baseoperator.py:421} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2025-01-05T21:08:39.423+0000] {http.py:139} INFO - Poking: api/
[2025-01-05T21:08:39.430+0000] {base.py:84} INFO - Retrieving connection 'user_api'
[2025-01-05T21:08:39.580+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2025-01-05T21:08:39.588+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-05T21:08:39.588+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=user_processing2_vsc, task_id=is_api_available, run_id=scheduled__2025-01-05T21:07:00+00:00, execution_date=20250105T210700, start_date=20250105T210839, end_date=20250105T210839
[2025-01-05T21:08:39.596+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-05T21:08:39.596+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-05T21:08:39.597+0000] {logging_mixin.py:190} INFO - Dag name:user_processing2_vsc queued_at:2025-01-05 21:08:35.806556+00:00
[2025-01-05T21:08:39.597+0000] {logging_mixin.py:190} INFO - Task hostname:cab0b5f06594 operator:HttpSensor
[2025-01-05T21:08:39.620+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-05T21:08:39.645+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-05T21:08:39.646+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
